# Nordic-darker color palette
#2e3440	user
#3b4252	dir
#434c5e	git
#4c566a	version
#5e81ac	doc (from dracula color palette)
#6272a4	time (from dracula color palette)

# some extra symbols
# î‚¶
# î‚´

#           _     _ 
#  ______ _(_) __| |
# |_  / _` | |/ _` |
#  / / (_| | | (_| |
# /___\__,_|_|\__,_|	zaid-hassan
 
# ---------------------------------------------------------------
format = """
[â–‘â–’â–“](#2e3440)\
$os\

$username\
[î‚°](fg:#2e3440 bg:#201f1f )\

$shell\
[î‚°](fg:#201f1f bg:#3b4252)\

$directory\
[î‚°](fg:#3b4252 bg:#434c5e)\

$git_branch\

$git_status\
[î‚°](fg:#434c5e bg:#4c566a)\

$c\
$python\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[î‚°](fg:#4c566a bg:#5e81ac)\

$docker_context\
[î‚°](fg:#5e81ac bg:#6272a4)\

$time\
[î‚° ](fg:#6272a4)\

\n
$cmd_duration\
$character\
"""
#add_newline = false

[line_break]
disabled = false

# [shell]
# disabled = false
# #bsh_indicator = "BSH"
# bash_indicator = "bsh"
# #fish_indicator = "FISH"
# fish_indicator = "ğŸŸ"
# #zsh_indicator = "ZSH"
# zsh_indicator =  "ğŸ’¤"

[username]
show_always = true
style_user = "bg:#2e3440"
format = '[$user ]($style)'
disabled = false

[os]
style = "bg:#2e3440"
disabled = true # Disabled by default

[shell]
fish_indicator = "ğŸŸ"
zsh_indicator =  "ğŸ’¤"
bash_indicator = "bsh"
powershell_indicator = 'ï‘ _'
unknown_indicator = 'mystery shell'
style = "bg:#201f1f"
format = '[$indicator ]($style)'
disabled = false

[directory]
style = "bg:#3b4252"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "â€¦/"

[directory.substitutions]
"Documents" = "ïœ˜ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "

[c]
symbol = "î˜ "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[python]
symbol = "î˜† "
style = "bg:#4c566a"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#5e81ac"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#434c5e"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#434c5e"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "î˜§ "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ïš¤ "
style = "bg:##434c5e"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#434c5e"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#6272a4"
format = '[ ïº $time ]($style)'
	
[character]
success_symbol = '[ âœ](#6272a4)'
error_symbol = '[ âœ](bold red)'
#style = "bg:#6272a4"

[cmd_duration]
min_time = 500
format = ' [$duration](#6272a4)'